version: '3'

volumes:
  pg_data_kitty:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kitty:/var/lib/postgresql/data

  backend:
    image: lacolle87/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: lacolle87/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: lacolle87/kittygram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend